-- Oracle Tables Schema
-- Provided by User

 TABLE TW_MIS_ADM.TWINSA_WORKTIME
(
  WORKDATE  DATE,
  SABUN     CHAR(6 BYTE),
  WORKTIME  CHAR(5 BYTE),
  OVERTIME  CHAR(5 BYTE)
);

 TABLE TW_MIS_ADM.TWINSA_WORKDAILY
(
  YYYYMM    CHAR(6 BYTE),
  SABUN     CHAR(6 BYTE),
  DEPTCODE  CHAR(6 BYTE),
  DAY01     CHAR(3 BYTE),
  DAY02     CHAR(3 BYTE),
  DAY03     CHAR(3 BYTE),
  DAY04     CHAR(3 BYTE),
  DAY05     CHAR(3 BYTE),
  DAY06     CHAR(3 BYTE),
  DAY07     CHAR(3 BYTE),
  DAY08     CHAR(3 BYTE),
  DAY09     CHAR(3 BYTE),
  DAY10     CHAR(3 BYTE),
  DAY11     CHAR(3 BYTE),
  DAY12     CHAR(3 BYTE),
  DAY13     CHAR(3 BYTE),
  DAY14     CHAR(3 BYTE),
  DAY15     CHAR(3 BYTE),
  DAY16     CHAR(3 BYTE),
  DAY17     CHAR(3 BYTE),
  DAY18     CHAR(3 BYTE),
  DAY19     CHAR(3 BYTE),
  DAY20     CHAR(3 BYTE),
  DAY21     CHAR(3 BYTE),
  DAY22     CHAR(3 BYTE),
  DAY23     CHAR(3 BYTE),
  DAY24     CHAR(3 BYTE),
  DAY25     CHAR(3 BYTE),
  DAY26     CHAR(3 BYTE),
  DAY27     CHAR(3 BYTE),
  DAY28     CHAR(3 BYTE),
  DAY29     CHAR(3 BYTE),
  DAY30     CHAR(3 BYTE),
  DAY31     CHAR(3 BYTE),
  REMARK    VARCHAR2(50 BYTE)
);

TABLE TW_MIS_ADM.TWINSA_MASTER
(
  SABUN         CHAR(6 BYTE),
  NAMEK         VARCHAR2(20 BYTE),
  NAMEE         VARCHAR2(20 BYTE),
  NAMEH         VARCHAR2(20 BYTE),
  JUMIN         VARCHAR2(32 BYTE),
  BIRTHDAY      CHAR(8 BYTE),
  BIRTHGUBUN    CHAR(1 BYTE),
  BONADDRESS    VARCHAR2(100 BYTE),
  ADDRESS       VARCHAR2(100 BYTE),
  POST          CHAR(6 BYTE),
  TEL           VARCHAR2(20 BYTE),
  DEPTTEL       VARCHAR2(20 BYTE),
  PAGER         VARCHAR2(20 BYTE),
  CONTRACT      CHAR(4 BYTE),
  CONTRACTDATE  DATE,
  INSCHOOL      CHAR(4 BYTE),
  PERMITSCHOOL  CHAR(4 BYTE),
  LASTSCHOOL    CHAR(4 BYTE),
  LASTSCHNAME   VARCHAR2(30 BYTE),
  LASTMAJOR     VARCHAR2(30 BYTE),
  STATUS        CHAR(1 BYTE),
  STATUSCAUSE   VARCHAR2(30 BYTE),
  STATUSDATE    DATE,
  DEPT          CHAR(6 BYTE),
  DEPT2         CHAR(6 BYTE),
  JIKJONG       CHAR(4 BYTE),
  JIKWI         CHAR(4 BYTE),
  JIKWI2        CHAR(4 BYTE),
  JIKMU         CHAR(4 BYTE),
  JIKGB         CHAR(2 BYTE),
  HOBONG        CHAR(2 BYTE),
  INDATE        DATE,
  INGUBUN       CHAR(4 BYTE),
  APPDATE       DATE,
  APPOINT       CHAR(4 BYTE),
  RELIGION      CHAR(4 BYTE),
  HOBBY         VARCHAR2(20 BYTE),
  SPECIAL       VARCHAR2(20 BYTE),
  HOUSE         VARCHAR2(20 BYTE),
  TRANSUSE      VARCHAR2(20 BYTE),
  OBSTACLE      VARCHAR2(20 BYTE),
  HEIGHT        NUMBER(3),
  WEIGHT        NUMBER(3),
  BLOOD         VARCHAR2(10 BYTE),
  EYEL          VARCHAR2(10 BYTE),
  EYER          VARCHAR2(10 BYTE),
  HEALTH        VARCHAR2(100 BYTE),
  MARRIAGEDATE  DATE,
  BOHUNGUBUN    VARCHAR2(30 BYTE),
  BOHUNREL      VARCHAR2(30 BYTE),
  ETC           VARCHAR2(2000 BYTE),
  CARDNO        CHAR(8 BYTE),
  MARRIAGE      CHAR(1 BYTE),
  ANNUITYDATE   DATE,
  ANNUITY       CHAR(1 BYTE),
  WRITEDATE     DATE,
  LICNO         VARCHAR2(20 BYTE),
  PHONGUBUN     CHAR(4 BYTE),
  NOJO          VARCHAR2(50 BYTE),
  CAREERREMARK  VARCHAR2(200 BYTE),
  AUTHORITY     CHAR(1 BYTE),
  GWOPEN        CHAR(1 BYTE)                    DEFAULT 'N',
  CONTENDDATE   DATE,
  ROTATION      CHAR(4 BYTE),
  JIKJONG_SUB   CHAR(4 BYTE),
  ORGCODE       CHAR(6 BYTE),
  PRN_DEPTNM    VARCHAR2(30 BYTE),
  YEARS_EMP     NUMBER
);

COMMENT ON TABLE TW_MIS_ADM.TWINSA_MASTER IS '인사마스터';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.SABUN IS '사원번호';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.NAMEK IS '한글명';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.NAMEE IS '영문명';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.NAMEH IS '한자명';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.JUMIN IS '주민번호';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.BIRTHDAY IS '생년월일';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.BIRTHGUBUN IS '양음구분 1양력, 2음력';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.BONADDRESS IS '본적';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.ADDRESS IS '주소';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.POST IS '우편번호';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.TEL IS '전화번호';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.DEPTTEL IS '부서전화번호';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.PAGER IS '휴대전화';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.CONTRACT IS '계약상태';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.CONTRACTDATE IS '계약일자';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.INSCHOOL IS '입사학력';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.PERMITSCHOOL IS '인정학력';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.LASTSCHOOL IS '최종학력';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.LASTSCHNAME IS '출신학교';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.LASTMAJOR IS '전공';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.STATUS IS '인사상태 0재직 1휴직 2퇴직예정 3 퇴직';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.STATUSCAUSE IS '퇴직사유';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.STATUSDATE IS '인사일자';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.DEPT IS '부서';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.JIKJONG IS '직종';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.JIKWI IS '직위';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.JIKMU IS '직무';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.JIKGB IS '직급';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.HOBONG IS '호봉';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.INDATE IS '입사일자';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.INGUBUN IS '입사구분';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.APPDATE IS '발령일자';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.APPOINT IS '발령구분';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.RELIGION IS '종교';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.HOBBY IS '취미';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.SPECIAL IS '특기';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.HOUSE IS '주거';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.TRANSUSE IS '출퇴근';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.OBSTACLE IS '장애여부';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.HEIGHT IS '신장';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.WEIGHT IS '체중';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.BLOOD IS '혈액형';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.EYEL IS '시력(좌)';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.EYER IS '시력(우)';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.HEALTH IS '건강상태';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.MARRIAGEDATE IS '결혼일자';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.BOHUNGUBUN IS '보훈구분';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.BOHUNREL IS '보훈관계';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.ETC IS '기타사항';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.MARRIAGE IS '결혼유무(1.미혼  2.기혼)';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.ANNUITYDATE IS '연금가입일자';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.ANNUITY IS '가입연금';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.WRITEDATE IS '인트라넷 개인정보 수정일자';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_MASTER.ORGCODE IS '기관코드';

CREATE TABLE TW_MIS_ADM.TWINSA_DEPT
(
  DEPT       CHAR(6 BYTE),
  DEPTNAME   VARCHAR2(30 BYTE),
  STARTDATE  DATE,
  GUBUN      CHAR(1 BYTE),
  CODE1      CHAR(6 BYTE),
  CODE2      CHAR(6 BYTE),
  CODE3      CHAR(6 BYTE),
  RANK       NUMBER(3),
  DELMARK    CHAR(1 BYTE),
  REMARK     CHAR(30 BYTE),
  ABBREV     CHAR(4 BYTE),
  CODE0      CHAR(6 BYTE)
);

COMMENT ON TABLE TW_MIS_ADM.TWINSA_DEPT IS '부서코드';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_DEPT.ABBREV IS '약칭';

TABLE TW_MIS_ADM.TWINSA_WORK_CALL
(
  SEQNO     NUMBER,
  SABUN     CHAR(6 BYTE),
  CALLDATE  DATE,
  FROMTIME  DATE,
  TOTIME    DATE,
  REMARK    VARCHAR2(2000 BYTE),
  PTNO      CHAR(8 BYTE)
)
TABLESPACE MIS_ADM_INSA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;

COMMENT ON TABLE TW_MIS_ADM.TWINSA_WORK_CALL IS 'ON CALL 현황';
COMMENT ON COLUMN TW_MIS_ADM.TWINSA_WORK_CALL.SEQNO IS '일련번호';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_WORK_CALL.CALLDATE IS 'CALL 일자';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_WORK_CALL.FROMTIME IS '근무시작시간 YYYY-MM-DD 24HH:MI';

COMMENT ON COLUMN TW_MIS_ADM.TWINSA_WORK_CALL.TOTIME IS '근무종료시간 YYYY-MM-DD 24HH:MI';
